get_beer:
    path: api/beers/{id}
    controller: App\PunkApi\Beers\Infrastructure\Controller\BeerController::get_beer
    methods: GET

list_beer:
    path: api/beers
    controller: App\PunkApi\Beers\Infrastructure\Controller\BeerController::list
    methods: GET